[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
cclibs = []
libmpi = "/disk/local/lib/libmpi.so"
mpiexec = "/disk/local/bin/mpiexec"
preloads = []
